import pandas as pd
import plotly.express as px
import streamlit as st

from utils.loader import load_json
from utils.sidebar import render_sidebar
from utils.theme import apply_theme


def parse_hour(label: str) -> int:
    parts = label.split()
    hour = int(parts[0])
    if "PM" in label and hour != 12:
        hour += 12
    if "AM" in label and hour == 12:
        hour = 0
    return hour


st.session_state["active_page"] = "Executive Dashboard"
apply_theme()
render_sidebar()

if not st.session_state.get("auth"):
    st.warning("Please login to access the Executive Dashboard.")
    st.switch_page("pages/1_Login.py")

sales = load_json("sales.json")
ai = load_json("ai.json")
inv = load_json("inventory.json")


def build_snapshot_pdf():
    """Lightweight PDF snapshot of key KPIs and alerts."""
    header_height = 60
    y = 760
    kpi_lines = [
        f"Today Revenue: AED {sales['today_sales']:,.0f}",
        f"Orders Today: {sales['orders_today']:,}",
        f"Avg Ticket: AED {sales['avg_ticket']:,.2f}",
        f"Profit Margin: {sales['profit_margin']*100:.1f}%",
    ]
    body_lines = kpi_lines + ["Executive Insights:"]
    body_lines.extend(
        [
            *ai.get("alerts", []),
            *[f"Low stock: {i['name']} ({i['stock']})" for i in inv["items"] if i["stock"] <= i["min"]],
            f"Predicted peak: {ai.get('prediction', {}).get('next_busy_hour', 'N/A')}",
        ]
    )

    def esc(txt: str) -> str:
        return txt.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")

    content = [
        "q",
        "0 0 0 rg",
        f"0 {792 - header_height} 612 {header_height} re f",
        "0.878 0.705 0.333 rg",
        f"0 {792 - header_height} 612 3 re f",
        "Q",
        "BT",
        "1 1 1 rg",
        "/F1 18 Tf",
        f"40 {y} Td",
        f"({esc('Lark Executive Snapshot')}) Tj",
        "/F1 11 Tf",
        "0 -20 Td",
        f"({esc('Generated by Quantex')}) Tj",
        "0 0 0 rg",
    ]
    y -= 50
    for line in body_lines:
        content.extend(["0 -18 Td", f"({esc(line)}) Tj"])
    content.append("ET\n")
    content_bytes = "\n".join(content).encode("latin-1", errors="ignore")

    objects = []
    objects.append("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n")
    objects.append("2 0 obj\n<< /Type /Pages /Count 1 /Kids [3 0 R] >>\nendobj\n")
    objects.append(
        "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        "/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n"
    )
    objects.append("4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n")
    objects.append(f"5 0 obj\n<< /Length {len(content_bytes)} >>\nstream\n{content_bytes.decode('latin-1')}\nendstream\nendobj\n")

    pdf_header = "%PDF-1.4\n"
    offsets, parts = [], [pdf_header]
    cursor = len(pdf_header)
    for obj in objects:
        offsets.append(cursor)
        parts.append(obj)
        cursor += len(obj)
    xref_start = cursor
    xref = f"xref\n0 {len(objects)+1}\n0000000000 65535 f \n" + "".join(f"{off:010d} 00000 n \n" for off in offsets)
    trailer = f"trailer\n<< /Size {len(objects)+1} /Root 1 0 R >>\nstartxref\n{xref_start}\n%%EOF"
    parts.append(xref)
    parts.append(trailer)
    return "".join(parts).encode("latin-1", errors="ignore")


# Header (reduced padding, micro stats)
st.markdown(
    """
    <div class="glass glass-strong glow-border animate-pop" style="padding: 14px 18px; position:relative; overflow:hidden;">
        <div style="position:absolute; inset:0; background: radial-gradient(circle at 20% 20%, rgba(27,118,255,0.12), transparent 35%); opacity:0.7;"></div>
        <div style="position:relative; display:flex; justify-content:space-between; align-items:flex-start;">
            <div>
                <div class="pill" style="background: rgba(27,118,255,0.16);">Live Executive Feed</div>
                <h2 style="margin: 4px 0 2px;">Insights Generated by QX for Larc Cafe</h2>
                <p style="color:#c8d6f5; margin:0;">Premium live view for ownership — every insight in AED with AI context.</p>
                <div style="color:#9fb0c7; margin-top:6px; font-size:12px;">Realtime Feed · AED Currency · AI Assisted · Demo Mode</div>
                <div style="margin-top:6px; color:#9fb0c7;"><span class="pulse-dot"></span> AI Active</div>
            </div>
            <div style="text-align:right; color:#9fb0c7;">
                <div style="font-size:12px;">Last updated:</div>
                <div style="font-weight:600;">realtime (demo mode)</div>
            </div>
        </div>
    </div>
    """,
    unsafe_allow_html=True,
)

# KPI cards with sparklines
spark_data = {
    "revenue": [sales["today_sales"] * x for x in [0.72, 0.91, 1.0]],
    "orders": [max(10, sales["orders_today"] * x) for x in [0.6, 0.82, 1.0]],
    "ticket": [max(10, sales["avg_ticket"] * x) for x in [0.85, 0.93, 1.0]],
    "margin": [max(0.2, sales["profit_margin"] * x) for x in [0.8, 0.9, 1.0]],
}

kpi_data = [
    {"label": "Today Revenue (AED)", "value": f"{sales['today_sales']:,.0f}", "icon": "💰", "sub": "↑ 18% vs yesterday", "glow": "glow-blue", "spark": spark_data["revenue"]},
    {"label": "Orders Today", "value": f"{sales['orders_today']:,}", "icon": "🧾", "sub": "Peak at 10AM", "glow": "glow-blue", "spark": spark_data["orders"]},
    {"label": "Avg Ticket (AED)", "value": f"{sales['avg_ticket']:,.2f}", "icon": "🎟️", "sub": "Strong upsells today", "glow": "glow-blue" if sales["avg_ticket"] > 30 else "", "spark": spark_data["ticket"]},
    {"label": "Profit Margin (%)", "value": f"{sales['profit_margin']*100:.1f}%", "icon": "📈", "sub": "Healthy", "glow": "glow-gold" if sales["profit_margin"] > 0.4 else "", "spark": [m * 100 for m in spark_data["margin"]]},
]

st.markdown("<div style='padding: 0 4px;'>", unsafe_allow_html=True)
kpi_cols = st.columns(4)
for col, card in zip(kpi_cols, kpi_data):
    fig_spark = px.line(y=card["spark"], height=70)
    fig_spark.update_traces(line=dict(color="#5FB1FF", width=2), marker=dict(size=4, color="#E0B455"))
    fig_spark.update_layout(
        margin=dict(l=10, r=10, t=10, b=10),
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        xaxis=dict(visible=False),
        yaxis=dict(visible=False),
    )
    col.markdown(
        f"""
        <div class="kpi-card {card.get('glow','')}" style="padding:16px;">
            <div style="display:flex; align-items:center; justify-content:space-between;">
                <div style="display:flex; align-items:center;">
                    <span class="kpi-icon">{card['icon']}</span>
                    <div style="color:#A9B8D3; font-size:13px;">{card['label']}</div>
                </div>
            </div>
            <div class="kpi-value fade-in">{card['value']}</div>
            <div class="kpi-sub">{card['sub']}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )
    col.plotly_chart(fig_spark, use_container_width=True, config={"displayModeBar": False})
st.markdown("</div>", unsafe_allow_html=True)

st.markdown('<div class="divider"></div>', unsafe_allow_html=True)

# Charts area (three columns on wide screens)
chart_cols = st.columns([1.4, 1.1, 1])

with chart_cols[0]:
    hourly_df = pd.DataFrame(sales["sales_by_hour"])
    hourly_df["hour_num"] = hourly_df["hour"].apply(parse_hour)
    hourly_df["prev_sales"] = hourly_df["sales"].shift(1)
    hourly_df["pct_diff"] = ((hourly_df["sales"] - hourly_df["prev_sales"]) / hourly_df["prev_sales"]).fillna(0) * 100
    fig_hourly = px.line(
        hourly_df,
        x="hour_num",
        y="sales",
        markers=True,
        title="Sales per Hour (AED)",
        template="plotly_dark",
        height=430,
    )
    fig_hourly.update_traces(
        line=dict(color="#1B76FF", width=4, shape="spline"),
        marker=dict(size=8, color="#5FB1FF", line=dict(width=1, color="#0b1626")),
        hovertemplate="Hour: %{x}:00<br>Sales: AED %{y:.0f}<br>Δ vs prev: %{customdata[0]:.1f}%<extra></extra>",
        customdata=hourly_df[["pct_diff"]],
        fill="tozeroy",
        fillcolor="rgba(27,118,255,0.10)",
    )
    predicted_peak = ai.get("prediction", {}).get("next_busy_hour")
    if predicted_peak:
        peak_num = parse_hour(predicted_peak)
        fig_hourly.add_vline(
            x=peak_num,
            line_color="#E0B455",
            line_width=2,
            line_dash="dash",
            annotation_text="AI: Expected Peak Hour",
            annotation_position="top right",
        )
    fig_hourly.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        margin=dict(l=10, r=10, t=40, b=10),
        font=dict(color="#E8EEF9"),
        hovermode="x unified",
        xaxis=dict(
            tickmode="array",
            tickvals=hourly_df["hour_num"],
            ticktext=hourly_df["hour"],
            title="",
            showgrid=False,
        ),
        yaxis=dict(showgrid=True, gridcolor="rgba(255,255,255,0.05)"),
    )
    st.plotly_chart(fig_hourly, use_container_width=True)

with chart_cols[1]:
    mix_df = pd.DataFrame(
        {"Category": list(sales["category_breakdown"].keys()), "Share": list(sales["category_breakdown"].values())}
    )
    mix_df["AED"] = mix_df["Share"] / 100 * sales["today_sales"]
    fig_mix = px.pie(
        mix_df,
        values="Share",
        names="Category",
        hole=0.68,
        color_discrete_sequence=["#1B76FF", "#E0B455", "#5FB1FF", "#9C7CFF"],
        title="Category Mix",
        height=430,
    )
    fig_mix.update_traces(
        hoverinfo="label+percent",
        textinfo="percent",
        pull=[0.02] * len(mix_df),
    )
    fig_mix.update_layout(
        annotations=[
            dict(text="Total Categories<br><b>4</b><br><span style='color:#9fb0c7;'>Tap to analyze</span>", x=0.5, y=0.5, font_size=12, showarrow=False)
        ],
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color="#E8EEF9"),
        margin=dict(l=0, r=0, t=40, b=0),
        showlegend=False,
    )
    st.plotly_chart(fig_mix, use_container_width=True)
    st.markdown("<div style='text-align:right; color:#9fb0c7; font-size:12px;'>Category Legend</div>", unsafe_allow_html=True)
    legend_lines = []
    colors = ["#1B76FF", "#E0B455", "#5FB1FF", "#9C7CFF"]
    for (_, row), color in zip(mix_df.iterrows(), colors):
        legend_lines.append(f"<span style='color:{color};'>●</span> {row['Category']} — AED {row['AED']:,.0f}")
    st.markdown("<br>".join(legend_lines), unsafe_allow_html=True)

with chart_cols[2]:
    top_items = sales.get(
        "top_items",
        [
            {"name": "Spanish Latte", "revenue": 1034},
            {"name": "Latte", "revenue": 738},
            {"name": "Cold Brew", "revenue": 620},
        ],
    )
    top_df = pd.DataFrame(top_items)
    fig_top = px.bar(
        top_df,
        x="revenue",
        y="name",
        orientation="h",
        title="Top 3 Items Today (AED)",
        color="revenue",
        color_continuous_scale=["#5FB1FF", "#1B76FF"],
        height=430,
    )
    fig_top.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color="#E8EEF9"),
        margin=dict(l=10, r=10, t=40, b=10),
        coloraxis_showscale=False,
    )
    st.plotly_chart(fig_top, use_container_width=True)

# Executive info row
info_cols = st.columns(3)
best_hour = max(sales["sales_by_hour"], key=lambda x: x["sales"])
fast_mover = ai.get("fast_movers", [{"item": "Spanish Latte", "rate": "3x faster than morning"}])[0]
profit_item = ai.get("profit_drivers", [{"item": "Spanish Latte", "margin": 0.72}])[0]
info_cards = [
    ("Best Hour Today", f"{best_hour['hour']} — AED {best_hour['sales']:,.0f}"),
    ("Fastest Moving Product", f"{fast_mover['item']} — {fast_mover.get('rate','')}".strip()),
    ("Highest Profit Item", f"{profit_item['item']} — {profit_item['margin']*100:.0f}% margin"),
]
for col, (title, val) in zip(info_cols, info_cards):
    col.markdown(
        f"""
        <div class="glass glass-strong animate-pop" style="padding:14px; min-height:90px;">
            <div class="pill" style="background: rgba(27,118,255,0.12);">{title}</div>
            <div style="font-size:16px; font-weight:700; margin-top:6px;">{val}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

# Executive insights
alerts = ai.get("alerts", [])
low_stock = [item for item in inv["items"] if item["stock"] <= item["min"]]
profit_notes = [f"{p['item']} — {p['margin']*100:.0f}% margin" for p in ai.get("profit_drivers", [])]
predicted_peak = ai.get("prediction", {}).get("next_busy_hour")

insight_cards = []
for a in alerts:
    card_type = "risk" if "under" in a.lower() or "increase" in a.lower() else "performance"
    insight_cards.append({"text": a, "type": card_type})
for i in low_stock:
    insight_cards.append({"text": f"Low stock: {i['name']} ({i['stock']} left)", "type": "risk"})
if predicted_peak:
    insight_cards.append({"text": f"Predicted peak at {predicted_peak} — align staffing.", "type": "performance"})
for note in profit_notes:
    insight_cards.append({"text": f"Profit driver: {note}", "type": "profit"})

st.markdown(
    """
    <div class="glass gold-frame ripple animate-pop" style="padding: 18px 20px; margin-top: 12px;">
        <div style="display:flex; align-items:center; gap:10px;">
            <div class="ai-avatar">🤖</div>
            <div>
                <div class="pill" style="background: rgba(224,180,85,0.14); color:#ffd78a; border-color: rgba(224,180,85,0.4);">QX Command</div>
                <h3 style="margin: 6px 0 4px;">Insights Generated by QX for Larc Cafe</h3>
            </div>
        </div>
    """,
    unsafe_allow_html=True,
)

card_cols = st.columns(2)
for idx, item in enumerate(insight_cards):
    color = {
        "performance": "rgba(27,118,255,0.18)",
        "profit": "rgba(224,180,85,0.18)",
        "risk": "rgba(255,77,77,0.18)",
    }.get(item["type"], "rgba(27,118,255,0.12)")
    border = {
        "performance": "rgba(27,118,255,0.45)",
        "profit": "rgba(224,180,85,0.6)",
        "risk": "rgba(255,99,99,0.6)",
    }.get(item["type"], "rgba(27,118,255,0.4)")
    with card_cols[idx % 2]:
        st.markdown(
            f"""
            <div class="glass animate-pop" style="border-color:{border}; box-shadow:0 0 12px {border}; background:{color};">
                {item['text']}
            </div>
            """,
            unsafe_allow_html=True,
        )

st.markdown("</div>", unsafe_allow_html=True)

# AI commentary strip
st.markdown(
    """
    <div class="glass animate-pop" style="border-left:4px solid #1B76FF; box-shadow: 0 0 16px rgba(27,118,255,0.25);">
        <strong>QX suggests preparing extra staff for 8PM peak hour.</strong>
    </div>
    """,
    unsafe_allow_html=True,
)

# PDF snapshot
pdf_bytes = build_snapshot_pdf()
st.download_button(
    "Download Executive Snapshot (PDF)",
    data=pdf_bytes,
    file_name="lark_executive_snapshot.pdf",
    mime="application/pdf",
    use_container_width=True,
)
